version: '3.8'

services:
  server:
    container_name: social-server
    restart: always
    image: social-server:latest
    build: ./server
    ports:
      - 3000:3000
  client:
    container_name: social-client
    restart: always
    image: social-client:latest
    build: ./client
    ports:
      - 4173:4173
